name: 'Beginning DevOps - Github Actions for AWS CLI'
description: 'GitHub Action for AWS CLI'
author: beginning-devops
branding:
  icon: 'cloud'
  color: 'blue'
runs:
  using: docker
  image: Dockerfile